linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - revive
    - gocyclo
    - misspell
    - unconvert
  disable:
    - golint  # Deprecated, replaced by revive
    - typecheck  # Disable typecheck to avoid issues with external libraries

linters-settings:
  gocyclo:
    min-complexity: 30
  revive:
    ignore-generated-header: true
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
  misspell:
    locale: US
  errcheck:
    check-type-assertions: true
    check-blank: false

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
    - linters:
        - revive
      text: "should have a package comment"
    - path: vendor/
      linters:
        - all
    - path: testdata/
      linters:
        - all
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true 